name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string
  workflow_call:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
    
    - name: Set up Java 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: gradle
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Get version from root package.json
      run: |
        # Read version from root package.json
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "Publishing Python client version: ${VERSION} (from root package.json)"
    
    - name: Update version in pyproject.toml
      run: |
        sed -i "s/^version = .*/version = \"${VERSION}\"/" pyproject.toml
    
    - name: Build package
      run: pnpm run build:py
    
    - name: Publish to PyPI
      run: |
        python -m twine upload ${{ github.workspace }}/clients/python/dist/*