name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
      create_release:
        description: 'Create GitHub release'
        type: boolean
        default: true

jobs:
  create-release:
    if: github.event_name == 'push' || inputs.create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION="${GITHUB_REF#refs/tags/v}"
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Version: ${VERSION}"

    - name: Generate changelog
      run: pnpm changelog

    - name: Commit changelog
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add CHANGELOG.md
        if ! git diff --cached --quiet; then
          git commit -m "docs(changelog): update for v${{ steps.version.outputs.version }}"
          git push origin HEAD:main
        fi
    
    - name: Create Release
      if: github.event_name == 'push' || inputs.create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        body: |
          ## Artissist Logger v${{ steps.version.outputs.version }}
          
          ### Installation
          
          **Python:**
          ```bash
          pip install artissist-logger==${{ steps.version.outputs.version }}
          ```
          
          **JavaScript/TypeScript:**
          ```bash
          npm install @artissist/logger@${{ steps.version.outputs.version }}
          ```
          
          ### What's Changed
          See [CHANGELOG.md](https://github.com/artissist/logger/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false
  
  publish-python:
    needs: create-release
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/publish-python.yml
    secrets: inherit
  
  publish-npm:
    needs: create-release
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for npm trusted publishing
    uses: ./.github/workflows/publish-npm.yml
    secrets: inherit